-- reload init.lua :luafile %
require "nvim-configs.options"
require "nvim-configs.whitespace"
require "nvim-configs.cursor-position"
require "nvim-configs.search-jumps"
require "nvim-configs.buffer-reload"
require "nvim-configs.diff-unsaved"
require "nvim-configs.file-dir-path"
require "nvim-configs.keymaps"
require "nvim-configs.cheatsheets"
require "nvim-configs.quickfix-nav"
-- require "nvim-configs.lazy"
require "nvim-configs.pack"
