-- reload init.lua :luafile %
require "javier.options"
require "javier.whitespace"
require "javier.cursor-position"
require "javier.search-jumps"
require "javier.buffer-reload"
require "javier.diff-unsaved"
require "javier.file-dir-path"
require "javier.quickfix-remap"
require "javier.keymaps"
require "javier.cheatsheets"
